'use client';
import {useState,useEffect,useRef} from 'react';
import {BookOpen,Copy,Check,Crown,Users,X} from 'lucide-react';
type P={id:string;name:string;score:number;ready:boolean;submitted:boolean;voted:boolean};
type C={id:string;text:string;mine?:boolean;real?:boolean;owner?:string;voters?:string[]};
type R={code:string;host:string;me:string;phase:string;round:number;deadline:number;serverNow:number;word:string;players:P[];myBluff:string;myVote:string;gains:Record<string,number>;choices:C[]};
type Seat={code:string;token:string};
const colors=['#f8df47','#fb8ba0','#80c8f8','#ab9cf5','#80ddb3','#ffae6d','#dbe677','#e2a5d8'];
export default function Game(){
 const [room,setRoom]=useState<R|null>(null),[seat,setSeat]=useState<Seat|null>(null),[name,setName]=useState(''),[code,setCode]=useState(''),[mode,setMode]=useState('create'),[draft,setDraft]=useState(''),[choice,setChoice]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[connection,setConnection]=useState(''),[rules,setRules]=useState(false),[copied,setCopied]=useState(false),[clock,setClock]=useState(Date.now());
 const offset=useRef(0),inflight=useRef(false),epoch=useRef(0);
 function accept(r:R){offset.current=r.serverNow-Date.now();setRoom(r);}
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get('room')){setCode(q.get('room')!.toUpperCase());setMode('join');}try{const s=JSON.parse(localStorage.getItem('word-bluff-seat')||'null');if(s?.token&&s?.code)setSeat(s);}catch{}},[]);
 useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),200);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(!seat)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;let failures=0;
 async function sync(){const requestEpoch=epoch.current;if(inflight.current){timer=setTimeout(sync,350);return;}try{const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...seat,action:'sync'})});const d=await res.json() as {room:R;token:string;error?:string};if(stopped||requestEpoch!==epoch.current){if(!stopped)timer=setTimeout(sync,500);return;}if(!res.ok){if(res.status===401||res.status===404){localStorage.removeItem('word-bluff-seat');setSeat(null);setRoom(null);setError(d.error||'Please rejoin the room.');return;}throw new Error(d.error);}accept(d.room);failures=0;setConnection('');}catch{if(!stopped){failures++;setConnection('Reconnecting… Your seat is saved.');}}if(!stopped)timer=setTimeout(sync,Math.min(1000*2**failures,5000));}void sync();return()=>{stopped=true;clearTimeout(timer);};},[seat]);
 useEffect(()=>{setDraft(room?.myBluff||'');setChoice('');},[room?.round,room?.phase]);
 async function act(action:string,extra:Record<string,unknown>={}){if(inflight.current)return;inflight.current=true;epoch.current++;setBusy(true);setError('');try{const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...seat,action,...extra})});const d=await res.json() as {room:R;token:string;error?:string};if(!res.ok)throw new Error(d.error||'Try again.');if(d.room){accept(d.room);if(action==='create'||action==='join'){const s={code:d.room.code,token:d.token};localStorage.setItem('word-bluff-seat',JSON.stringify(s));setSeat(s);}}else{localStorage.removeItem('word-bluff-seat');setSeat(null);setRoom(null);}}catch(e){setError(e instanceof Error?e.message:'Connection lost. Try again.');}finally{inflight.current=false;setBusy(false);}}
 useEffect(()=>{
  if(!rules)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('[role="dialog"]');const buttons=dialog?.querySelectorAll<HTMLElement>('button');buttons?.[0]?.focus();
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setRules(false);if(e.key==='Tab'&&buttons?.length){const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};
 },[rules]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'read_word_bluff_game',description:'Read the current player-visible room, phase, choices, and scores. Hidden answers and other players’ seat credentials are never included.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');return room?{code:room.code,phase:room.phase,round:room.round,word:room.word,players:room.players,choices:room.choices}:{phase:'entry'};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[room]);
 const sec=room?.deadline?Math.max(0,Math.ceil((room.deadline-clock-offset.current)/1000)):0;
 const me=room?.players.find(p=>p.id===room.me),host=room?.host===room?.me;
 const ranks=room?[...room.players].sort((a,b)=>b.score-a.score):[];
 async function copy(){if(!room)return;try{await navigator.clipboard.writeText(`${location.origin}/?room=${room.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError(`Share room code ${room.code}.`);}}
 return <div className="shell"><header><a className="brand" href="/" onClick={e=>{if(room)e.preventDefault();}}><span className="mark">W<span>B</span></span>word bluff<span className="dot">.</span></a><button className="text-button" onClick={()=>setRules(true)}><BookOpen size={17}/> How to play</button></header><main>
 {!room?<div className="entry"><section className="intro"><span className="eyebrow">■ THE WORD GAME OF WELL-TOLD LIES</span><h1>Big words.<br/>Bigger <em>bluffs.</em></h1><p>Make up a meaning. Find the real one.<br/>See how well your friends can lie.</p><div className="facts"><span><Users size={18}/> 2–8 players</span><span>6 rounds</span><span>≈ 10 minutes</span></div><div className="example"><span className="eyebrow">YOUR NEXT WORD COULD BE</span><h2>absquatulate<span>?</span></h2><p>A fancy way to disappear? A dance move?<br/>Your bluff is as good as theirs.</p><span className="stamp">SOUNDS LEGIT.</span></div></section><section className="entry-card"><div className="card-top"><span className="eyebrow">LET’S PLAY</span><span>01 / 06</span></div><h2>Bring your<br/>best poker face.</h2><div className="tabs"><button className={mode==='create'?'active':''} onClick={()=>setMode('create')}>Host a game</button><button className={mode==='join'?'active':''} onClick={()=>setMode('join')}>Join a game</button></div><form onSubmit={e=>{e.preventDefault();void act(mode,{name,code:code.trim().toUpperCase()});}}><label htmlFor="name">YOUR NAME</label><input id="name" maxLength={18} required autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/>{mode==='join'&&<><label htmlFor="code">ROOM CODE</label><input id="code" className="code-input" minLength={5} maxLength={5} required autoComplete="off" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} placeholder="ABCDE"/></>}<button className="primary" disabled={busy||!name.trim()||(mode==='join'&&code.length!==5)}>{busy?'Connecting…':mode==='create'?'Create a room':'Join room'}</button></form><p className="note">{seat?'Restoring your seat…':mode==='create'?'Get a room code. Send it to your friends.':'Same room code. Your own device.'}</p>{error&&<p className="error" role="alert">{error}</p>}<div className="entry-bottom"><span className="dots"><i/><i/><i/></span>One room. Everyone’s in on it.</div></section></div>:<div className="game"><section><div className="room-bar"><span className="eyebrow">ROOM <strong>{room.code}</strong></span><button className="text-button" onClick={copy}><Copy size={15}/>{copied?'Link copied':'Invite friends'}</button></div>{connection&&<p className="connection" role="status">{connection}</p>}{error&&<p className="error" role="alert">{error}</p>}
 {room.phase==='lobby'?<div className="stage"><span className="eyebrow">THE GANG’S ALMOST HERE</span><h1>A room full<br/>of <em>bluffers.</em></h1><p>Send your friends this code. They join on their own device.</p><button className="big-code" onClick={copy} aria-label="Copy invite link">{room.code}<Copy size={22}/></button><div className="seats">{room.players.map((p,i)=><div className="seat" key={p.id}><span className="avatar" style={{background:colors[i]}}>{p.name[0].toUpperCase()}</span><strong>{p.name}{p.id===room.me?' (you)':''}</strong>{p.id===room.host&&<Crown size={17}/>}</div>)}{room.players.length===1&&<div className="seat waiting"><span className="avatar">?</span>Waiting for a friend</div>}</div>{host?<button className="primary" disabled={busy||room.players.length<2} onClick={()=>act('start')}>{room.players.length<2?'Waiting for one more…':'Start the game'}</button>:<p className="wait">{room.players.find(p=>p.id===room.host)?.name} will start the game.</p>}<button className="leave" disabled={busy} onClick={()=>act('leave')}>Leave room</button></div>:<><div className="round-strip"><span>ROUND <b>{String(room.round).padStart(2,'0')}</b> / 06</span><div className="round-dots">{Array.from({length:6},(_,i)=><i className={i<room.round?'filled':''} key={i}/>)}</div><span>{room.phase==='write'?'01 · WRITE':room.phase==='guess'?'02 · GUESS':room.phase==='reveal'?'03 · REVEAL':'FINAL RESULTS'}</span></div>
 {(room.phase==='write'||room.phase==='guess')&&<div className="stage"><div className="stage-top"><span className="eyebrow">{room.phase==='write'?'WHAT ON EARTH DOES THIS MEAN?':'ONE OF THESE IS THE TRUTH.'}</span><div className={'timer '+(sec<=10?'urgent':'')}>{sec}<small>SEC</small></div></div><h1 className="word">{room.word}<span>.</span></h1><p>{room.phase==='write'?'Invent a definition that sounds like it belongs in a dictionary.':'Spot the real meaning. You can’t pick your own bluff.'}</p><div className="time-track"><span style={{width:`${sec/(room.phase==='write'?45:25)*100}%`}}/></div>{room.phase==='write'?<>{room.myBluff?<div className="locked"><span className="eyebrow"><Check size={17}/> YOUR BLUFF IS LOCKED IN</span><p>{room.myBluff}</p><small>Keep a straight face. Guessing starts when the timer ends.</small></div>:<form onSubmit={e=>{e.preventDefault();void act('bluff',{text:draft});}}><label htmlFor="bluff">YOUR MADE-UP DEFINITION</label><textarea id="bluff" maxLength={180} minLength={3} required value={draft} onChange={e=>setDraft(e.target.value)} placeholder="The surprisingly official-sounding art of…" disabled={sec===0}/><div className="input-meta"><span>Make it believable. Or make it brilliant.</span><span>{draft.length}/180</span></div><button className="primary" disabled={busy||draft.trim().length<3||sec===0}>Lock in my bluff</button></form>}<p className="progress">{room.players.filter(p=>p.submitted).length} of {room.players.length} bluffs locked in</p></>:<><div className="choices">{room.choices.map((c,i)=><button key={c.id} className={'choice '+((room.myVote||choice)===c.id?'selected':'')} disabled={busy||!!room.myVote||c.mine||sec===0} onClick={()=>setChoice(c.id)}><span className="letter">{String.fromCharCode(65+i)}</span><span>{c.text}{c.mine&&<small>YOUR BLUFF</small>}</span>{(room.myVote||choice)===c.id&&<Check size={20}/>}</button>)}</div>{room.myVote?<p className="progress">✓ Guess locked in. The truth is coming.</p>:<button className="primary" disabled={busy||!choice||sec===0} onClick={()=>act('vote',{choice})}>Lock in my guess</button>}<p className="progress">{room.players.filter(p=>p.voted).length} of {room.players.length} guesses locked in</p></>}</div>}
 {room.phase==='reveal'&&<div className="stage"><span className="eyebrow">THE DICTIONARY HAS SPOKEN</span><h1 className="word">{room.word}<span>.</span></h1><div className="truth"><span className="eyebrow"><Check size={17}/> THE REAL DEFINITION</span><p>{room.choices.find(c=>c.real)?.text}</p></div><h3>Who fooled whom?</h3><div>{room.choices.filter(c=>!c.real).map(c=><div className="reveal-row" key={c.id}><p>{c.text}</p><div><strong>{c.owner?room.players.find(p=>p.id===c.owner)?.name:'Game decoy'}</strong><span>{c.voters?.length?`Fooled ${c.voters.map(id=>room.players.find(p=>p.id===id)?.name).join(', ')}`:'No one fell for it'}</span></div></div>)}</div><p className="round-result">You earned <strong>+{room.gains[room.me]||0}</strong> this round.{room.myVote===room.choices.find(c=>c.real)?.id?' You found the truth!':''}</p><div className="ready-actions"><button className="secondary" disabled={busy||me?.ready} onClick={()=>act('ready')}>{me?.ready?'✓ You’re ready':'I’m ready'}</button>{host&&<button className="primary" disabled={busy||!room.players.every(p=>p.ready)} onClick={()=>act('next')}>{room.round===6?'Show final results':'Next round'}</button>}</div><p className="progress">{room.players.filter(p=>p.ready).length}/{room.players.length} ready{!host?' · Waiting for the host to advance':''}</p></div>}
 {room.phase==='over'&&<div className="stage final"><span className="eyebrow">SIX WORDS. COUNTLESS LIES.</span><Crown size={54} className="winner-crown"/><h1>{ranks.filter(p=>p.score===ranks[0].score).length>1?'A shared':'The master'}<br/><em>victory.</em></h1><p className="winner-names">{ranks.filter(p=>p.score===ranks[0].score).map(p=>p.name).join(' & ')}</p><p>{ranks[0].score} points · {ranks.filter(p=>p.score===ranks[0].score).length>1?'Joint winners':'Champion bluffer'}</p><div className="final-scores">{ranks.map((p,i)=><div key={p.id}><span>{i===0?'★':ranks.findIndex(x=>x.score===p.score)+1}</span><strong>{p.name}{p.id===room.me?' (you)':''}</strong><b>{p.score}</b></div>)}</div>{host?<button className="primary" disabled={busy} onClick={()=>act('restart')}>Play again</button>:<p className="wait">The host can start another game.</p>}</div>}
 </>}
 </section><aside><div className="score-title"><h2>{room.phase==='lobby'?'The players':'Leaderboard'}</h2><span>{room.players.length}/8</span></div>{ranks.map(p=><div className="score-row" key={p.id}><span className="avatar" style={{background:colors[room.players.findIndex(x=>x.id===p.id)]}}>{p.name[0].toUpperCase()}</span><div><strong>{p.name}</strong><small>{p.id===room.host?'Host':p.id===room.me?'You':`Player ${room.players.findIndex(x=>x.id===p.id)+1}`}</small></div>{room.phase==='lobby'?<Check size={16}/>:<b>{p.score}</b>}{room.phase==='reveal'&&<span className="gain">+{room.gains[p.id]||0}</span>}</div>)}<div className="scoring"><span className="eyebrow">A GOOD LIE PAYS OFF</span><p><b>+2</b> Find the real definition</p><p><b>+1</b> Each player you fool</p></div><span className="side-wordmark">TRUST<br/>NO WORD.</span></aside></div>}
 </main><footer><span>A LITTLE WORDPLAY. A LOT OF DECEPTION.</span><span>NO DICTIONARIES ALLOWED.</span></footer>
 {rules&&<div className="backdrop" onClick={()=>setRules(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="rules-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close rules" onClick={()=>setRules(false)}><X/></button><span className="eyebrow">THE VERY OFFICIAL RULES</span><h2 id="rules-title">How to bluff.</h2><ol><li><strong>Write a lie · 45 seconds</strong><p>Everyone gets the same unusual word. Invent a convincing definition and lock it in.</p></li><li><strong>Find the truth · 25 seconds</strong><p>Pick the real meaning from the shuffled definitions. You can’t pick your own bluff.</p></li><li><strong>Collect your points</strong><p>Earn 2 points for finding the truth, plus 1 for every opponent who picks your bluff.</p></li><li><strong>Six rounds. One winner—or a tie.</strong><p>Everyone marks ready after the reveal; the host advances. Highest total wins. Ties share the win.</p></li></ol><p className="rule-note">2 players? We add two game decoys each round. They earn nobody points. Miss a timer? That action earns no points. Rooms last four hours.</p><button className="primary" onClick={()=>setRules(false)}>Got it. Let’s bluff.</button></section></div>}
 </div>;
}



